### ISSUE TITLE
Duplicate images created on multiple clicks on Submit

### ISSUE THREAD

**Issue by akylus** [Ajayvardhanreddy/flames#1]

**Comment by Ajayvardhanreddy** [comment]
Thank you bro! Yes, duplicate images are created on multiple clicks. I will update.

**Comment by akylus** [comment]
Sure, lookioing forward to it!

**Comment by Ajayvardhanreddy** [comment]
*Updated bro!*

https://ajayvardhanreddy.github.io/flames/

**Comment by akylus** [comment]
Great job, Ajay!
But once I submit, I am unable to try for different names. 
Try to fix that, or you can just add a note saying: 'Please refresh the page if you want to try for different names'

**Comment by akylus** [comment]
Closing this issue! Good job on the website!

**Comment by Ajayvardhanreddy** [comment]
Okay bro! I will fix it. And Thank you so much.
